apiVersion: apps/v1
kind: Deployment
metadata:
    name: install-app
    labels:
      app : install-app
spec:
  selector:
    matchLabels:
      app: install-app
  template:
    metadata:
      labels:
        app: install-app
    spec:
      restartPolicy: Always
      containers:
      - image: 881379168558.dkr.ecr.us-west-2.amazonaws.com/install-app:latest
        imagePullPolicy: Always
        name: install-app
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 96Mi
        name: install-app
        envFrom:
          - secretRef:
              name: ds-secrets
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: install-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: install-app
  minReplicas: 1
  maxReplicas: 2
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 95
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 95
---
apiVersion: v1
kind: Service
metadata:
  name: install-app-service
  #namespace: default
  labels:
    app:  install-app
spec:
  type: ClusterIP
  selector:
    app:  install-app
  ports:
  - protocol: TCP
    #name: 
    port: 80
    targetPort: 80
