apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: install-app-hpa
  namespace: data-science
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: install-app
  minReplicas: 1
  maxReplicas: 3
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80