apiVersion: apps/v1
kind: Deployment
metadata:
    name: install-app
    labels:
      app : install-app
spec:
  selector:
    matchLabels:
      app: install-app
  template:
    metadata:
      labels:
        app: install-app
    spec:
      containers:
      - image: gcr.io/gyra-1558028521907/install-app:v9.1
        imagePullPolicy: Always
        name: install-app
        env:
        - name: mongodbRead
          value: "bW9uZ29kYitzcnY6Ly9haXJmbG93OmtBQ3cyTHR4Z0Z6ZVB0bkBneXJhbWFpcy1wcm9kdWN0aW9uLmxod3RiLm1vbmdvZGIubmV0L2d5cmFtYWlzP3JldHJ5V3JpdGVzPXRydWUmcmVhZFByZWZlcmVuY2U9c2Vjb25kYXJ5JnJlYWRQcmVmZXJlbmNlVGFncz1ub2RlVHlwZTpBTkFMWVRJQ1Mmdz1tYWpvcml0eQ=="
---
apiVersion: v1
kind: Service
metadata:
  name: install-service
  namespace: default
  labels:
    app:  install-app
spec:
  type: ClusterIP
  selector:
    app:  install-app
  ports:
  - protocol: TCP
    #name: 
    port: 80
    targetPort: 80