# ubuntu
FROM ubuntu:latest
RUN apt-get update && apt-get -y install cron
RUN apt -y install python3
RUN apt -y install python3-pip
# Copy hello-cron file to the cron.d directory
COPY /app/cron /etc/cron.d/cron
# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/cron
# Apply cron job
RUN crontab /etc/cron.d/cron

COPY . /app
WORKDIR /app
RUN pip3 install pandas numpy flask flask_cors dnspython pymongo holidays gunicorn

ENTRYPOINT ["./app/gunicorn.sh"]
